name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Azure subscription
      run: az account set --subscription c32b3936-2faf-4d97-9c79-7c937acfc324

    - name: Trigger Azure ML job
      run: |
        az ml job create --file job.yml \
          --resource-group azurecertification \
          --workspace-name AzureCertification-Dev



