name: Code Checks

on:
  pull_request:  # Trigger workflow on PR creation

jobs:
  linting:
    name: Run Flake8 Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: flake8 . --count --max-line-length=120 --statistics

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: linting  # Runs after linting
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Pytest
        run: pytest tests/
