name: PR Code Verification

on:
  pull_request:  # Triggers the workflow on PR creation

jobs:
  verify-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge"
