name: Train and Deploy Model

on:
  push:
    branches:
      - main  # Runs workflow when pushing to main branch

jobs:
  experiment:
    name: Train in Development
    runs-on: ubuntu-latest
    environment: development  # Runs in the Dev environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}
          
      - name: Run Experiment in Development
        run: |
              az extension add --name ml --yes
              az ml job create --file job-dev.yml --stream \
                  --resource-group azurecertification \
                  --workspace-name AzureCertification-Dev


  production:
    name: Train in Production
    runs-on: ubuntu-latest
    environment: production  # Runs in the Prod environment
    needs: experiment  # Runs only if the experiment job succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds:${{ secrets.AZURE_CREDENTIALS_PROD}}

      - name: Run Training in Production
        run: |
            az extension add --name ml --yes
            az ml job create --file job-dev.yml --stream \
                --resource-group azurecertification \
                --workspace-name AzureCertification-Dev
